### ISSUE TITLE
Search site

### ISSUE THREAD

**Issue by dhnazarenko** [lmachens/photoplay#13]
![Bildschirmfoto 2021-05-25 um 12 13 44](https://user-images.githubusercontent.com/82373303/119481129-a9e11300-bd52-11eb-9d83-cdf11ec7c37f.png)

## User:

As a user want to search a movie or a tv-show.

## Todos

- [ ]  Fetch API with filter function
- [ ]  Add input type search
- [ ]  Request time handle function 
- [ ]  Show results filtered by movies and tv shows
