### ISSUE TITLE
TV show details

### ISSUE THREAD

**Issue by dhnazarenko** [lmachens/photoplay#4]
![Bildschirmfoto 2021-05-25 um 12 00 27](https://user-images.githubusercontent.com/82373303/119479323-cf6d1d00-bd50-11eb-90b7-18035b5f5f6e.png)

## User: 

As a user i want to have a detailed overview with movie trailer,  ranking, description, episodes.

## Todos:

- [x]  Fetch movie details
- [x]  Add back button
- [ ]  Show movie trailer
- [ ] Show title and genre
- [x] Show ranking
- [ ] show description
- [x] Watch now button
- [ ] List episodes with title, duration and download option
- [x] Add menu on bottom
